//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APK1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        APK1.ServiceReference1.HelloWorldResponse HelloWorld(APK1.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<APK1.ServiceReference1.HelloWorldResponse> HelloWorldAsync(APK1.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento expresion del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MultiplicacionImplicita", ReplyAction="*")]
        APK1.ServiceReference1.MultiplicacionImplicitaResponse MultiplicacionImplicita(APK1.ServiceReference1.MultiplicacionImplicitaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MultiplicacionImplicita", ReplyAction="*")]
        System.Threading.Tasks.Task<APK1.ServiceReference1.MultiplicacionImplicitaResponse> MultiplicacionImplicitaAsync(APK1.ServiceReference1.MultiplicacionImplicitaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento expresion del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarParentesisBalanceados", ReplyAction="*")]
        APK1.ServiceReference1.VerificarParentesisBalanceadosResponse VerificarParentesisBalanceados(APK1.ServiceReference1.VerificarParentesisBalanceadosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarParentesisBalanceados", ReplyAction="*")]
        System.Threading.Tasks.Task<APK1.ServiceReference1.VerificarParentesisBalanceadosResponse> VerificarParentesisBalanceadosAsync(APK1.ServiceReference1.VerificarParentesisBalanceadosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento expresion del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarSintaxis", ReplyAction="*")]
        APK1.ServiceReference1.VerificarSintaxisResponse VerificarSintaxis(APK1.ServiceReference1.VerificarSintaxisRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarSintaxis", ReplyAction="*")]
        System.Threading.Tasks.Task<APK1.ServiceReference1.VerificarSintaxisResponse> VerificarSintaxisAsync(APK1.ServiceReference1.VerificarSintaxisRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento expresion del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConvertirAPostfija", ReplyAction="*")]
        APK1.ServiceReference1.ConvertirAPostfijaResponse ConvertirAPostfija(APK1.ServiceReference1.ConvertirAPostfijaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConvertirAPostfija", ReplyAction="*")]
        System.Threading.Tasks.Task<APK1.ServiceReference1.ConvertirAPostfijaResponse> ConvertirAPostfijaAsync(APK1.ServiceReference1.ConvertirAPostfijaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento expresionPostfija del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EvaluarPostfija", ReplyAction="*")]
        APK1.ServiceReference1.EvaluarPostfijaResponse EvaluarPostfija(APK1.ServiceReference1.EvaluarPostfijaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EvaluarPostfija", ReplyAction="*")]
        System.Threading.Tasks.Task<APK1.ServiceReference1.EvaluarPostfijaResponse> EvaluarPostfijaAsync(APK1.ServiceReference1.EvaluarPostfijaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public APK1.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(APK1.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public APK1.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(APK1.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MultiplicacionImplicitaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MultiplicacionImplicita", Namespace="http://tempuri.org/", Order=0)]
        public APK1.ServiceReference1.MultiplicacionImplicitaRequestBody Body;
        
        public MultiplicacionImplicitaRequest() {
        }
        
        public MultiplicacionImplicitaRequest(APK1.ServiceReference1.MultiplicacionImplicitaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MultiplicacionImplicitaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string expresion;
        
        public MultiplicacionImplicitaRequestBody() {
        }
        
        public MultiplicacionImplicitaRequestBody(string expresion) {
            this.expresion = expresion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MultiplicacionImplicitaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MultiplicacionImplicitaResponse", Namespace="http://tempuri.org/", Order=0)]
        public APK1.ServiceReference1.MultiplicacionImplicitaResponseBody Body;
        
        public MultiplicacionImplicitaResponse() {
        }
        
        public MultiplicacionImplicitaResponse(APK1.ServiceReference1.MultiplicacionImplicitaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MultiplicacionImplicitaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MultiplicacionImplicitaResult;
        
        public MultiplicacionImplicitaResponseBody() {
        }
        
        public MultiplicacionImplicitaResponseBody(string MultiplicacionImplicitaResult) {
            this.MultiplicacionImplicitaResult = MultiplicacionImplicitaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarParentesisBalanceadosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarParentesisBalanceados", Namespace="http://tempuri.org/", Order=0)]
        public APK1.ServiceReference1.VerificarParentesisBalanceadosRequestBody Body;
        
        public VerificarParentesisBalanceadosRequest() {
        }
        
        public VerificarParentesisBalanceadosRequest(APK1.ServiceReference1.VerificarParentesisBalanceadosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerificarParentesisBalanceadosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string expresion;
        
        public VerificarParentesisBalanceadosRequestBody() {
        }
        
        public VerificarParentesisBalanceadosRequestBody(string expresion) {
            this.expresion = expresion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarParentesisBalanceadosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarParentesisBalanceadosResponse", Namespace="http://tempuri.org/", Order=0)]
        public APK1.ServiceReference1.VerificarParentesisBalanceadosResponseBody Body;
        
        public VerificarParentesisBalanceadosResponse() {
        }
        
        public VerificarParentesisBalanceadosResponse(APK1.ServiceReference1.VerificarParentesisBalanceadosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerificarParentesisBalanceadosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool VerificarParentesisBalanceadosResult;
        
        public VerificarParentesisBalanceadosResponseBody() {
        }
        
        public VerificarParentesisBalanceadosResponseBody(bool VerificarParentesisBalanceadosResult) {
            this.VerificarParentesisBalanceadosResult = VerificarParentesisBalanceadosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarSintaxisRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarSintaxis", Namespace="http://tempuri.org/", Order=0)]
        public APK1.ServiceReference1.VerificarSintaxisRequestBody Body;
        
        public VerificarSintaxisRequest() {
        }
        
        public VerificarSintaxisRequest(APK1.ServiceReference1.VerificarSintaxisRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerificarSintaxisRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string expresion;
        
        public VerificarSintaxisRequestBody() {
        }
        
        public VerificarSintaxisRequestBody(string expresion) {
            this.expresion = expresion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarSintaxisResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarSintaxisResponse", Namespace="http://tempuri.org/", Order=0)]
        public APK1.ServiceReference1.VerificarSintaxisResponseBody Body;
        
        public VerificarSintaxisResponse() {
        }
        
        public VerificarSintaxisResponse(APK1.ServiceReference1.VerificarSintaxisResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerificarSintaxisResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool VerificarSintaxisResult;
        
        public VerificarSintaxisResponseBody() {
        }
        
        public VerificarSintaxisResponseBody(bool VerificarSintaxisResult) {
            this.VerificarSintaxisResult = VerificarSintaxisResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertirAPostfijaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertirAPostfija", Namespace="http://tempuri.org/", Order=0)]
        public APK1.ServiceReference1.ConvertirAPostfijaRequestBody Body;
        
        public ConvertirAPostfijaRequest() {
        }
        
        public ConvertirAPostfijaRequest(APK1.ServiceReference1.ConvertirAPostfijaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConvertirAPostfijaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string expresion;
        
        public ConvertirAPostfijaRequestBody() {
        }
        
        public ConvertirAPostfijaRequestBody(string expresion) {
            this.expresion = expresion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertirAPostfijaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertirAPostfijaResponse", Namespace="http://tempuri.org/", Order=0)]
        public APK1.ServiceReference1.ConvertirAPostfijaResponseBody Body;
        
        public ConvertirAPostfijaResponse() {
        }
        
        public ConvertirAPostfijaResponse(APK1.ServiceReference1.ConvertirAPostfijaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConvertirAPostfijaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConvertirAPostfijaResult;
        
        public ConvertirAPostfijaResponseBody() {
        }
        
        public ConvertirAPostfijaResponseBody(string ConvertirAPostfijaResult) {
            this.ConvertirAPostfijaResult = ConvertirAPostfijaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EvaluarPostfijaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EvaluarPostfija", Namespace="http://tempuri.org/", Order=0)]
        public APK1.ServiceReference1.EvaluarPostfijaRequestBody Body;
        
        public EvaluarPostfijaRequest() {
        }
        
        public EvaluarPostfijaRequest(APK1.ServiceReference1.EvaluarPostfijaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EvaluarPostfijaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string expresionPostfija;
        
        public EvaluarPostfijaRequestBody() {
        }
        
        public EvaluarPostfijaRequestBody(string expresionPostfija) {
            this.expresionPostfija = expresionPostfija;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EvaluarPostfijaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EvaluarPostfijaResponse", Namespace="http://tempuri.org/", Order=0)]
        public APK1.ServiceReference1.EvaluarPostfijaResponseBody Body;
        
        public EvaluarPostfijaResponse() {
        }
        
        public EvaluarPostfijaResponse(APK1.ServiceReference1.EvaluarPostfijaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EvaluarPostfijaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double EvaluarPostfijaResult;
        
        public EvaluarPostfijaResponseBody() {
        }
        
        public EvaluarPostfijaResponseBody(double EvaluarPostfijaResult) {
            this.EvaluarPostfijaResult = EvaluarPostfijaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : APK1.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<APK1.ServiceReference1.WebService1Soap>, APK1.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APK1.ServiceReference1.HelloWorldResponse APK1.ServiceReference1.WebService1Soap.HelloWorld(APK1.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            APK1.ServiceReference1.HelloWorldRequest inValue = new APK1.ServiceReference1.HelloWorldRequest();
            inValue.Body = new APK1.ServiceReference1.HelloWorldRequestBody();
            APK1.ServiceReference1.HelloWorldResponse retVal = ((APK1.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<APK1.ServiceReference1.HelloWorldResponse> APK1.ServiceReference1.WebService1Soap.HelloWorldAsync(APK1.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<APK1.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            APK1.ServiceReference1.HelloWorldRequest inValue = new APK1.ServiceReference1.HelloWorldRequest();
            inValue.Body = new APK1.ServiceReference1.HelloWorldRequestBody();
            return ((APK1.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APK1.ServiceReference1.MultiplicacionImplicitaResponse APK1.ServiceReference1.WebService1Soap.MultiplicacionImplicita(APK1.ServiceReference1.MultiplicacionImplicitaRequest request) {
            return base.Channel.MultiplicacionImplicita(request);
        }
        
        public string MultiplicacionImplicita(string expresion) {
            APK1.ServiceReference1.MultiplicacionImplicitaRequest inValue = new APK1.ServiceReference1.MultiplicacionImplicitaRequest();
            inValue.Body = new APK1.ServiceReference1.MultiplicacionImplicitaRequestBody();
            inValue.Body.expresion = expresion;
            APK1.ServiceReference1.MultiplicacionImplicitaResponse retVal = ((APK1.ServiceReference1.WebService1Soap)(this)).MultiplicacionImplicita(inValue);
            return retVal.Body.MultiplicacionImplicitaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<APK1.ServiceReference1.MultiplicacionImplicitaResponse> APK1.ServiceReference1.WebService1Soap.MultiplicacionImplicitaAsync(APK1.ServiceReference1.MultiplicacionImplicitaRequest request) {
            return base.Channel.MultiplicacionImplicitaAsync(request);
        }
        
        public System.Threading.Tasks.Task<APK1.ServiceReference1.MultiplicacionImplicitaResponse> MultiplicacionImplicitaAsync(string expresion) {
            APK1.ServiceReference1.MultiplicacionImplicitaRequest inValue = new APK1.ServiceReference1.MultiplicacionImplicitaRequest();
            inValue.Body = new APK1.ServiceReference1.MultiplicacionImplicitaRequestBody();
            inValue.Body.expresion = expresion;
            return ((APK1.ServiceReference1.WebService1Soap)(this)).MultiplicacionImplicitaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APK1.ServiceReference1.VerificarParentesisBalanceadosResponse APK1.ServiceReference1.WebService1Soap.VerificarParentesisBalanceados(APK1.ServiceReference1.VerificarParentesisBalanceadosRequest request) {
            return base.Channel.VerificarParentesisBalanceados(request);
        }
        
        public bool VerificarParentesisBalanceados(string expresion) {
            APK1.ServiceReference1.VerificarParentesisBalanceadosRequest inValue = new APK1.ServiceReference1.VerificarParentesisBalanceadosRequest();
            inValue.Body = new APK1.ServiceReference1.VerificarParentesisBalanceadosRequestBody();
            inValue.Body.expresion = expresion;
            APK1.ServiceReference1.VerificarParentesisBalanceadosResponse retVal = ((APK1.ServiceReference1.WebService1Soap)(this)).VerificarParentesisBalanceados(inValue);
            return retVal.Body.VerificarParentesisBalanceadosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<APK1.ServiceReference1.VerificarParentesisBalanceadosResponse> APK1.ServiceReference1.WebService1Soap.VerificarParentesisBalanceadosAsync(APK1.ServiceReference1.VerificarParentesisBalanceadosRequest request) {
            return base.Channel.VerificarParentesisBalanceadosAsync(request);
        }
        
        public System.Threading.Tasks.Task<APK1.ServiceReference1.VerificarParentesisBalanceadosResponse> VerificarParentesisBalanceadosAsync(string expresion) {
            APK1.ServiceReference1.VerificarParentesisBalanceadosRequest inValue = new APK1.ServiceReference1.VerificarParentesisBalanceadosRequest();
            inValue.Body = new APK1.ServiceReference1.VerificarParentesisBalanceadosRequestBody();
            inValue.Body.expresion = expresion;
            return ((APK1.ServiceReference1.WebService1Soap)(this)).VerificarParentesisBalanceadosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APK1.ServiceReference1.VerificarSintaxisResponse APK1.ServiceReference1.WebService1Soap.VerificarSintaxis(APK1.ServiceReference1.VerificarSintaxisRequest request) {
            return base.Channel.VerificarSintaxis(request);
        }
        
        public bool VerificarSintaxis(string expresion) {
            APK1.ServiceReference1.VerificarSintaxisRequest inValue = new APK1.ServiceReference1.VerificarSintaxisRequest();
            inValue.Body = new APK1.ServiceReference1.VerificarSintaxisRequestBody();
            inValue.Body.expresion = expresion;
            APK1.ServiceReference1.VerificarSintaxisResponse retVal = ((APK1.ServiceReference1.WebService1Soap)(this)).VerificarSintaxis(inValue);
            return retVal.Body.VerificarSintaxisResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<APK1.ServiceReference1.VerificarSintaxisResponse> APK1.ServiceReference1.WebService1Soap.VerificarSintaxisAsync(APK1.ServiceReference1.VerificarSintaxisRequest request) {
            return base.Channel.VerificarSintaxisAsync(request);
        }
        
        public System.Threading.Tasks.Task<APK1.ServiceReference1.VerificarSintaxisResponse> VerificarSintaxisAsync(string expresion) {
            APK1.ServiceReference1.VerificarSintaxisRequest inValue = new APK1.ServiceReference1.VerificarSintaxisRequest();
            inValue.Body = new APK1.ServiceReference1.VerificarSintaxisRequestBody();
            inValue.Body.expresion = expresion;
            return ((APK1.ServiceReference1.WebService1Soap)(this)).VerificarSintaxisAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APK1.ServiceReference1.ConvertirAPostfijaResponse APK1.ServiceReference1.WebService1Soap.ConvertirAPostfija(APK1.ServiceReference1.ConvertirAPostfijaRequest request) {
            return base.Channel.ConvertirAPostfija(request);
        }
        
        public string ConvertirAPostfija(string expresion) {
            APK1.ServiceReference1.ConvertirAPostfijaRequest inValue = new APK1.ServiceReference1.ConvertirAPostfijaRequest();
            inValue.Body = new APK1.ServiceReference1.ConvertirAPostfijaRequestBody();
            inValue.Body.expresion = expresion;
            APK1.ServiceReference1.ConvertirAPostfijaResponse retVal = ((APK1.ServiceReference1.WebService1Soap)(this)).ConvertirAPostfija(inValue);
            return retVal.Body.ConvertirAPostfijaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<APK1.ServiceReference1.ConvertirAPostfijaResponse> APK1.ServiceReference1.WebService1Soap.ConvertirAPostfijaAsync(APK1.ServiceReference1.ConvertirAPostfijaRequest request) {
            return base.Channel.ConvertirAPostfijaAsync(request);
        }
        
        public System.Threading.Tasks.Task<APK1.ServiceReference1.ConvertirAPostfijaResponse> ConvertirAPostfijaAsync(string expresion) {
            APK1.ServiceReference1.ConvertirAPostfijaRequest inValue = new APK1.ServiceReference1.ConvertirAPostfijaRequest();
            inValue.Body = new APK1.ServiceReference1.ConvertirAPostfijaRequestBody();
            inValue.Body.expresion = expresion;
            return ((APK1.ServiceReference1.WebService1Soap)(this)).ConvertirAPostfijaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APK1.ServiceReference1.EvaluarPostfijaResponse APK1.ServiceReference1.WebService1Soap.EvaluarPostfija(APK1.ServiceReference1.EvaluarPostfijaRequest request) {
            return base.Channel.EvaluarPostfija(request);
        }
        
        public double EvaluarPostfija(string expresionPostfija) {
            APK1.ServiceReference1.EvaluarPostfijaRequest inValue = new APK1.ServiceReference1.EvaluarPostfijaRequest();
            inValue.Body = new APK1.ServiceReference1.EvaluarPostfijaRequestBody();
            inValue.Body.expresionPostfija = expresionPostfija;
            APK1.ServiceReference1.EvaluarPostfijaResponse retVal = ((APK1.ServiceReference1.WebService1Soap)(this)).EvaluarPostfija(inValue);
            return retVal.Body.EvaluarPostfijaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<APK1.ServiceReference1.EvaluarPostfijaResponse> APK1.ServiceReference1.WebService1Soap.EvaluarPostfijaAsync(APK1.ServiceReference1.EvaluarPostfijaRequest request) {
            return base.Channel.EvaluarPostfijaAsync(request);
        }
        
        public System.Threading.Tasks.Task<APK1.ServiceReference1.EvaluarPostfijaResponse> EvaluarPostfijaAsync(string expresionPostfija) {
            APK1.ServiceReference1.EvaluarPostfijaRequest inValue = new APK1.ServiceReference1.EvaluarPostfijaRequest();
            inValue.Body = new APK1.ServiceReference1.EvaluarPostfijaRequestBody();
            inValue.Body.expresionPostfija = expresionPostfija;
            return ((APK1.ServiceReference1.WebService1Soap)(this)).EvaluarPostfijaAsync(inValue);
        }
    }
}
